# Generated by Django 3.0.2 on 2020-01-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counterinfo',
            name='cName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
