# Generated by Django 3.0.2 on 2020-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongogo', '0002_auto_20200130_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=255, unique=True)),
                ('cDate', models.DateField()),
                ('cUrl', models.URLField()),
            ],
        ),
    ]
