# Generated by Django 3.0.2 on 2020-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongogo', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cDate',
            field=models.CharField(max_length=255),
        ),
    ]
