# Generated by Django 3.0.2 on 2020-02-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongogo', '0004_auto_20200203_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PttArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=255, unique=True)),
                ('cDate', models.CharField(max_length=255)),
                ('cUrl', models.URLField()),
                ('cPush', models.IntegerField()),
            ],
        ),
    ]
