# Generated by Django 3.0.2 on 2020-02-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongogo', '0005_pttarticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pttarticles',
            name='cPush',
        ),
    ]
